/**
 * Wails binding type re-exports and secondary type definitions.
 * Primary types come from wailsjs/go/models.ts (auto-generated by Wails).
 * This file provides frontend-side convenience wrappers and call signatures.
 */

// Re-export Wails auto-generated model types (namespaced under `main` in models.ts)
import { main } from '../../wailsjs/go/models';
export const RandomParams = main.RandomParams;
export type RandomParams = main.RandomParams;
export const TimezoneResult = main.TimezoneResult;
export type TimezoneResult = main.TimezoneResult;
export const CronParseResult = main.CronParseResult;
export type CronParseResult = main.CronParseResult;
export const ToolMeta = main.ToolMeta;
export type ToolMeta = main.ToolMeta;
export const ActionDef = main.ActionDef;
export type ActionDef = main.ActionDef;

// Re-export Wails binding method functions
export {
  JsonFormat,
  JsonMinify,
  JsonValidate,
  Base64EncodeText,
  Base64DecodeText,
  Base64EncodeFile,
  Base64DecodeFile,
  SelectInputFile,
  SelectOutputFile,
  TimestampToDate,
  DateToTimestamp,
  MultiTimezone,
  YamlFormat,
  YamlValidate,
  YamlToJSON,
  XmlFormat,
  XmlMinify,
  XmlValidate,
  RandomGenerate,
  CronParse,
  CronValidate,
  CronNextN,
  UrlEncode,
  UrlDecode,
  UrlParseQuery,
  HashGenerate,
  HashGenerateAll,
  JwtDecode,
  UuidGenerate,
  UuidValidate,
  RegexTest,
  RegexReplace,
  ClipboardWrite,
  GetDataDir,
  GetToolList,
  GetAppVersion,
} from '../../wailsjs/go/main/App';

/** Type-safe Wails Go method call signature */
export type GoMethodFn<T = any> = (...args: any[]) => Promise<T>;

/** Standard Wails error format (from Go error → Promise reject) */
export interface WailsError {
  message: string;
  raw: unknown;
}
